### PR TITLE
Add Default-Values from Body-Models

### PR DESCRIPTION
**Pull request by letsbyteit**
If set, use the default-value of the given model. The property where the default-value is located is called 'default'. Be careful, because 'default' is a reserved keyword.

### CODE REVIEW

**Comment by letsbyteit** [comment]
Just discovered that there are some problems with complex models, maybe you could help fix this?

Model (part of it)
screen shot 2016-03-14 at 05 24 17

Parsed (part of it)
screen shot 2016-03-14 at 05 22 08

**Comment by nosyjoe** [comment]
the pull request looks good to me, I'll merge it. thanks for fixing the swagger-typo. that was kind of embarrassing...

**Comment by nosyjoe** [comment]
about your issue in the complex model: seems to me that it could be fixed by changing the `"type": "int"` to `"integer"` (e.g.  for key `"program_ids"`), what do you think?

**Comment by letsbyteit** [comment]
@nosyjoe Yeah, you're right. Didn't see that. I'm on it to fix the generator-framework, so has nothing to do with the pull-request. ;-)

**Pull request merged**
